language: node_js
node_js:
  - "10"
install:
  - cd ..
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start mol/app/demo
  - node mol/app/demo/-/node.test.js
  - npm start mol/app/hello
  - npm start mol/app/supplies
  - npm start mol/app/habhub
  - npm start mol/app/todomvc
  - npm start mol/perf/sierp
  - npm start mol/perf/uibench
  - npm start mol/perf/dbmon 
  - npm start mol/app/bench/bench
  - npm start mol/app/bench/list/mol
  - npm start mol/app/bench/list/tsx
  - npm start mol/app/bench/chart/rope/mol
  - npm start mol/app/bench/chart/bar/mol
  - npm start mol/app/taxon
  - npm start mol/app/taxon/demo
  - npm start mol/app/users
  - npm start mol/mem
  - npm start mol/app/quine
  - npm start mol/app/lamps
  - npm start mol/app/files/demo
  - npm start mol/app/questions
  - npm start mol/app/calc
  - npm start mol/chat/service
  - npm start mol/app/life
  - npm start mol/time/all
  - npm start mol/plot/all
  - npm start mol/fiber
  - npm start mol/app/report
  - npm start mol/app/tree
  - npm start mol/app/request
  - npm start mol/app/rdf
  - npm start mol/app/jsperf
  - npm start mol/app/issues
  - npm start mol/syntax2
  - npm start mol/func/sandbox/demo
  - rm mol/.gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
notifications:
  slack: mam-mol:Z7vokFhXaSrMlPXzq6L93bUj
