name: Deploy

on:
  push:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout sources
      uses: actions/checkout@v1
    
    - name: Checkout MAM
      uses: actions/checkout@v1
      with:
        repository: eigenmethod/mam
        ref: master
        path: mam
    
    - name: Build app
      run: |
        pwd
        cd ..
        ls
        mkdir mam/mol
        mv mol/* mol/.nojekyll mam/mol
        cd mam
        yarn
        yarn start mol/app/demo
        node ./mol/app/demo/-/node.test.js
        node ./mol/build/-/node.test.js mol/app/hello
        node ./mol/build/-/node.test.js mol/app/supplies
        node ./mol/build/-/node.test.js mol/perf/sierp
        node ./mol/build/-/node.test.js mol/perf/uibench
        node ./mol/build/-/node.test.js mol/perf/dbmon 
        node ./mol/build/-/node.test.js mol/app/taxon
        node ./mol/build/-/node.test.js mol/app/taxon/demo
        node ./mol/build/-/node.test.js mol/app/users
        node ./mol/build/-/node.test.js mol/mem
        node ./mol/build/-/node.test.js mol/app/quine
        node ./mol/build/-/node.test.js mol/app/questions
        node ./mol/build/-/node.test.js mol/chat/service
        node ./mol/build/-/node.test.js mol/time/all
        node ./mol/build/-/node.test.js mol/plot/all
        node ./mol/build/-/node.test.js mol/fiber/demo
        node ./mol/build/-/node.test.js mol/app/report
        node ./mol/build/-/node.test.js mol/syntax2
        node ./mol/build/-/node.test.js mol/func/sandbox/demo
        
    - name: Deploy on GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: '../mam/mol'

